# Generated by Django 5.1.15 on 2026-09-29 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(max_length=60, unique=True, verbose_name='装订索书号')),
                ('location', models.CharField(max_length=100, verbose_name='装订后位置')),
                ('bound_month', models.DateField(blank=True, null=True, verbose_name='装订月份')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '装订册',
                'ordering': ['call_number'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('regular', '普通期'), ('combined', '合刊')], default='regular', max_length=10, verbose_name='类型')),
                ('issue_month', models.DateField(help_text='只取年月；合刊可只填起始月', verbose_name='发行年月')),
                ('issue_month_end', models.DateField(blank=True, help_text='合刊/跨年卷的覆盖结束月', null=True, verbose_name='发行截止年月')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '发行期',
                'ordering': ['issue_month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IssueNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, max_length=20, verbose_name='卷')),
                ('number', models.CharField(max_length=20, verbose_name='期')),
                ('sort_key', models.PositiveIntegerField(default=0, help_text='馆员录入的编号顺序，跨年卷按编号顺序而非月份排列', verbose_name='排序键')),
            ],
            options={
                'verbose_name': '期号',
                'ordering': ['sort_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='刊名')),
                ('issn', models.CharField(blank=True, max_length=9, verbose_name='ISSN')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='出版者')),
                ('status', models.CharField(choices=[('active', '在刊'), ('ceased', '停刊')], default='active', max_length=10, verbose_name='出版状态')),
                ('ceased_month', models.DateField(blank=True, null=True, verbose_name='停刊月份')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IssueNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='如 no.3-4，仅作展示', max_length=40, verbose_name='封面标识')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serials.issue')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serials.issuenumber')),
            ],
            options={
                'unique_together': {('issue', 'number')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='numbers',
            field=models.ManyToManyField(related_name='issues', through='serials.IssueNumbering', to='serials.issuenumber'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=40, unique=True, verbose_name='条码')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='馆藏位置')),
                ('status', models.CharField(choices=[('available', '在馆'), ('checked_out', '借出'), ('lost', '丢失'), ('bound', '已装订')], default='available', max_length=12, verbose_name='馆藏状态')),
                ('accessioned_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(help_text='实物对应的发行期；合刊实物只指向这一个 Issue，对多个期号的覆盖由 IssueNumbering 表达', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='serials.issue')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='serials.title')),
            ],
            options={
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='BindingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_location', models.CharField(blank=True, max_length=100, verbose_name='装订前位置')),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='serials.binding')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binding_entry', to='serials.item')),
            ],
            options={
                'unique_together': {('item', 'binding')},
            },
        ),
        migrations.AddField(
            model_name='binding',
            name='items',
            field=models.ManyToManyField(related_name='bindings', through='serials.BindingEntry', to='serials.item'),
        ),
        migrations.AddField(
            model_name='issuenumber',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='serials.title'),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='serials.title'),
        ),
        migrations.AddField(
            model_name='binding',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='serials.title'),
        ),
        migrations.AlterUniqueTogether(
            name='issuenumber',
            unique_together={('title', 'volume', 'number')},
        ),
    ]
