# Generated by Django 5.1.15 on 2026-09-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuenumbering',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numberings', to='serials.issue'),
        ),
        migrations.AlterField(
            model_name='issuenumbering',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numberings', to='serials.issuenumber'),
        ),
    ]
