# Generated by Django 5.1.15 on 2026-10-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '在馆'), ('checked_out', '借出'), ('lost', '丢失'), ('bound', '已装订'), ('quarantine', '待隔离'), ('in_treatment', '处理中'), ('treatment_done', '处理完成'), ('discarded', '报废')], default='available', max_length=16, verbose_name='馆藏状态'),
        ),
        migrations.CreateModel(
            name='ConservationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(choices=[('damp', '受潮'), ('pest', '虫害'), ('mold', '霉变'), ('damage', '破损'), ('other', '其他')], max_length=10, verbose_name='处理原因')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='情况说明')),
                ('status', models.CharField(choices=[('quarantine', '待隔离'), ('in_treatment', '处理中'), ('completed', '处理完成'), ('closed', '已恢复'), ('discarded', '已报废')], default='quarantine', max_length=12, verbose_name='处理单状态')),
                ('temporary_location', models.CharField(blank=True, help_text='隔离/送修期间实体所在位置，定位与时间轴据此展示', max_length=100, verbose_name='临时位置')),
                ('restore_location', models.CharField(blank=True, help_text='处理完成返还后的去向；默认回原位置（装订册内实体回册位置）', max_length=100, verbose_name='恢复位置')),
                ('binding_call_number', models.CharField(blank=True, max_length=60, verbose_name='所属装订册（快照）')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='开立幂等键')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='办结时间')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conservation_orders', to='serials.binding')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_orders', to='serials.item')),
            ],
            options={
                'verbose_name': '保护处理单',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('open', '开立处理单'), ('handover_out', '送出交接'), ('assessment', '状况评估'), ('complete', '处理完成'), ('handover_in', '返还交接'), ('discard', '报废')], max_length=15, verbose_name='事件类型')),
                ('idempotency_key', models.CharField(max_length=64, verbose_name='幂等键')),
                ('version', models.PositiveIntegerField(verbose_name='应用后处理单版本')),
                ('from_status', models.CharField(blank=True, choices=[('quarantine', '待隔离'), ('in_treatment', '处理中'), ('completed', '处理完成'), ('closed', '已恢复'), ('discarded', '已报废')], max_length=12, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('quarantine', '待隔离'), ('in_treatment', '处理中'), ('completed', '处理完成'), ('closed', '已恢复'), ('discarded', '已报废')], max_length=12, verbose_name='新状态')),
                ('condition_note', models.CharField(blank=True, max_length=255, verbose_name='状况评估')),
                ('location', models.CharField(blank=True, help_text='交接/评估时实体所在位置，会同步为处理单的临时位置', max_length=100, verbose_name='事件后所在位置')),
                ('operator', models.CharField(blank=True, max_length=40, verbose_name='经办人')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='serials.conservationorder')),
            ],
            options={
                'verbose_name': '保护处理事件',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='conservationorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('quarantine', 'in_treatment', 'completed'))), fields=('item',), name='uniq_active_conservation_per_item'),
        ),
        migrations.AddConstraint(
            model_name='conservationevent',
            constraint=models.UniqueConstraint(fields=('order', 'idempotency_key'), name='uniq_cons_event_key_per_order'),
        ),
    ]
