# Generated by Django 5.1.15 on 2026-10-02 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '在馆'), ('checked_out', '借出'), ('lost', '丢失'), ('bound', '已装订'), ('quarantine_pending', '待隔离'), ('in_treatment', '处理中'), ('treatment_done', '处理完成'), ('discarded', '报废')], default='available', max_length=20, verbose_name='馆藏状态'),
        ),
        migrations.CreateModel(
            name='PreservationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(choices=[('water', '受潮'), ('pest', '虫害'), ('mold', '霉变'), ('other', '其他')], max_length=10, verbose_name='受损原因')),
                ('status', models.CharField(choices=[('quarantine_pending', '待隔离'), ('in_treatment', '处理中'), ('treatment_done', '处理完成'), ('returned', '已返还'), ('discarded', '已报废')], default='quarantine_pending', max_length=20, verbose_name='处理单状态')),
                ('condition_assessment', models.TextField(blank=True, verbose_name='条件评估')),
                ('temporary_location', models.CharField(blank=True, max_length=100, verbose_name='临时位置')),
                ('restore_location', models.CharField(blank=True, help_text='处理完成后返还上架的位置；默认取开单时的实际位置', max_length=100, verbose_name='恢复位置')),
                ('binding_call_number', models.CharField(blank=True, max_length=60, verbose_name='处置时所在装订册')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='闭环时间')),
                ('item', models.ForeignKey(help_text='被处置的实物；发行/条码/装订关系不因处理而改变', on_delete=django.db.models.deletion.PROTECT, related_name='preservation_orders', to='serials.item')),
            ],
            options={
                'verbose_name': '保护处理单',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PreservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('open', '开立处理单'), ('handover', '交接送出'), ('assess', '条件评估'), ('complete', '处理完成'), ('return', '返还上架'), ('discard', '报废')], max_length=10, verbose_name='事件类型')),
                ('idempotency_key', models.CharField(max_length=64, verbose_name='幂等键')),
                ('version', models.PositiveIntegerField(verbose_name='事件版本')),
                ('applied', models.BooleanField(default=True, help_text='False 表示迟到/过期事件：仅保留审计，不改变处置状态', verbose_name='已生效')),
                ('location', models.CharField(blank=True, help_text='交接时的临时位置 / 返还时的恢复位置', max_length=100, verbose_name='事件位置')),
                ('condition_assessment', models.TextField(blank=True, verbose_name='条件评估')),
                ('actor', models.CharField(blank=True, max_length=60, verbose_name='经手人')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='serials.preservationorder')),
            ],
            options={
                'verbose_name': '保护处理事件',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='preservationorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['quarantine_pending', 'in_treatment', 'treatment_done'])), fields=('item',), name='unique_active_preservation_order_per_item'),
        ),
        migrations.AlterUniqueTogether(
            name='preservationevent',
            unique_together={('order', 'idempotency_key')},
        ),
    ]
